= Continuous Threat Modeling

== Term

Continous Threat Modeling includes processes and tools to support threat modeling in DevOps teams in a frequent and highly team-adopted manner.

== Motivation & problem statement

I am very interested in security and how to implement it in way, that it is not regarded as "additional workload", but as business as usual. In the DevOps context, there are several examples in the past going the same path from "annoying" to "normal":

* *Documentation:* At the beginning of my career, documentation was the last step before going live. Implementation was already done, but documentation was still to do. And in many cases, documentation was done in a word processor such as Microsoft Word and archived in a document management system. Thanks to the available toolchains, documentation is now implemented into the development flow: It can be stored as code (and - not less important - along with the code) and it can be consumed not only on your local machine with your word processor, but also be rendered as a website by your ci/cd pipelines, if required.
* *Testing:* Testing is another example for this process. In ealier years, testing was outsourced to a specialized enterprise unit, where testers and test automators followed the instructions from the test designers to assure software quality. Thanks to new approaches (e. g. test driven development), highly automated testing tools on all levels (unit tests, integration tests, acceptance tests for UIs, APIs and other interfaces) and the inclusion of those tools into the ci/cd pipelines, tests are a fundamental part of development and not a stage after development.

The evolution of these two examples were some kind of forced by the increasing speed of development cycles. The phases "design - plan - implement - test - document" are merging and speeding up. We do not have a 8 month cycle, but a few-hours to few-days cycle.

If we have a look at security aspects (and threat modeling is a quite big one, as it covers many layers from a high level system view and to technical implementation details of single components) it seems to be different: 

* Many companies have governance rules to do threat modeling on project kick-off, once a year or on major system changes. These triggering events do not happen very frequently and seem to be a relict from times where development cycles are much slower.
* Threat modeling was seperated into an analysis part, where a security specialist discusses with the project's IT architect, and an implementation part, where developers implemented measures specified in the first part without further knowledge of the context.

From my point of view, this has some negative consequences:

* Threat modeling is not done as often as it should be done. Although we have a daily-changing system, we regard threat modeling as a one-off effort and and as a "tick in the box".
* Threat modeling is totally seperate from usual work. It feels like a "special event" (in a negative sense) and an additional effort not directly linked with our daily business.
* The context (Why do we do threat modeling?) gets lost for the team members as they only implement countermeasures without being part of the discussion about the actual threat, the relevance/importance and the available options to manage the resulting risks. This leads to the feeling, that threat modeling is something the enterprise wants from the team (it should be the other way around: threat modeling should be the responsibility of the team; the enterprice can of course assist with specialized personell).

== Desired state

// TODO Describe desired state in more detail
* Team members are part of the process from beginning on
* Doing threat modeling feels very much like development (toolchain, process)
* Team feels responsible for process and outcome

== Implementation

I think, there are four pillars of threat modeling, which in combination have a very broad coverage:

* Creative approach (_"Imagine, that the largest newspaper company reports about an intrusion into your system. What could have happend?"_)
** Can be fun for the team
** Requires individual engagement
** Supports thinking out of the box
* Scenario-based approach (_"Imagine, that an attacker has gained shell access in our web application docker container. What could happen next? How could we stop him?"_)
** Considers defense-in-depth
** Feels real and the team gets a sense for security 
** Triggers the team to deep-dive into technical considerations
* Systematic approach (_"Let's systematically walk through the STRIDE categories and analyse potential threats."_)
** Assures that we do not forget to think about a threat category (no or at least less blind spots)
** Guides the team through the categories and increases awareness
* Automatic/Rule-based approach (_"Let's model our system, feed the data into an intelligence and ask it for probable risks, e. g. SQL injection for any web application connected to a database."_)
** Covers no-brainers
** Frees up time for the other approaches
** Helps to comply with market or enterprise standards

// TODO Describe the process and how tools can help
// TODO Describe maturity levels and step-by-step implementation (start small)

== Threat Modeling Tools

There are several tools available for threat modeling, both commercial and free/open-source. The following list contains an imcomplete and random selection of some tools crossing my way:

* https://threagile.io/[Threagile]
* https://owasp.org/www-project-threat-dragon/[OWASP Threat Dragon]
* https://threatspec.org/[threatspec]

== Further reading

* https://www.threatmodelingmanifesto.org/[Threat Modeling Manifesto]